blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    CountryListView,
    SearchPostView,
)
from . import views


urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('search/', SearchPostView.as_view(), name='search-post'),
    path('country/<int:id>/', CountryListView.as_view(), name='blog-country'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('about/', views.about, name='blog-about'),
    path('like/<int:pk>/', views.PostLikeView, name='like-post'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard', include('jet.dashboard.urls', 'jet-dashboard')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image



class Country(models.Model):
    country_name = models.CharField(max_length=50, verbose_name='Vùng miền')

    def __str__(self):
        return self.country_name


class Place(models.Model):
    place_name = models.CharField(max_length=50, verbose_name='Địa điểm')
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.place_name
        

class Post(models.Model):
    title = models.CharField('Tiêu đề' ,max_length=100)
    content = models.TextField('Nội dung')
    published = models.BooleanField(default=True)
    date_posted = models.DateTimeField(default=timezone.now)
    liked = models.ManyToManyField(User, default=None, blank=True, related_name='liked')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, default='')
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_pics', verbose_name='image')


    def __str__(self):
        return self.title
    
    @property
    def num_likes(self):
        return self.liked.all().count()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 800 or img.width > 600:
            output_size = (800, 600)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='album_post', blank=True, null=True, verbose_name='images')

    def __str__(self):
        return self.post.title + " Image"
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    content = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, default=None, blank=True, related_name='likes')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    def __str__(self):
        return '{} by {}'.format(self.post.title, str(self.user.username))


    
    

blog/forms.py
from django import forms
from .models import Comment, Images, Post


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 50, 'style': 'resize:none', 'placeholder': 'Nhập gì đó...'}), label='')

    class Meta:
        model = Comment
        fields = ('content',)

class ImagesForm(forms.ModelForm):
    images = forms.ImageField(label='Hình ảnh')
    class Meta:
        model = Images
        fields = ('images',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'country', 'place', 'image',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.db.models import Count
from django.views.generic.edit import FormMixin
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect
from .forms import CommentForm, ImagesForm, PostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic import (
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    RedirectView
)
from .models import Post, Comment, Country, Place, Images


def home(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }

    return render(request, 'blog/home.html', context) # get context and request to home.html


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html' # default: <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted'] # sorted date posted from new to old
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        context['featured_post'] = Post.objects.annotate(like_count=Count('liked')).order_by('-like_count')[:3]
        return context


class SearchPostView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Post.objects.filter(title__icontains=query)
        else:
            return Post.objects.all()
            

class CountryListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(CountryListView, self).get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        context['country'] = Country.objects.filter(id=self.kwargs.get('id')).first()
        context['featured_post'] = Post.objects.annotate(like_count=Count('liked')).order_by('-like_count')[:5]
        return context

    def get_queryset(self):
        country = get_object_or_404(Country, id=self.kwargs.get('id'))
        return Post.objects.filter(country=country).order_by('-date_posted')


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html' # default: <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        return context
    
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class PostDetailView(SuccessMessageMixin, FormMixin, DetailView):
    form_class = CommentForm
    model = Post
    success_message = 'Bình luận thành công!'
    
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        country = Post.objects.get(id=self.kwargs.get('pk')).country
        context['form'] = CommentForm
        context['countries'] = Country.objects.all()
        context['comments'] = self.object.comments.filter(approved=True, parent__isnull=True)
        context['post_list'] = Post.objects.filter(country_id=country).order_by('-date_posted')[:3]
        return context

    def post(self, request, *args, **kwargs):
        comm_form = self.form_class(request.POST)
        if comm_form.is_valid():
            parent_obj = None
            try:
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                if parent_obj:
                    replay_comment = comm_form.save(commit=False)
                    replay_comment.parent = parent_obj
            comm_form.instance.post = Post.objects.get(id=self.kwargs.get('pk'))
            comm_form.instance.user = self.request.user
            comm_form.save()


class PostCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_form.html'
    ImagesFormSet = modelformset_factory(Images, form=ImagesForm, extra=3)
    success_message = 'Tạo bài viết thành công!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["postForm"] = PostForm
        context['countries'] = Country.objects.all()
        context["formset"] = self.ImagesFormSet(queryset=Images.objects.none())
        return context
    
    def post(self, request, *args, **kwargs):
        postForm = self.form_class(request.POST, request.FILES or None)
        formset = self.ImagesFormSet(request.POST, request.FILES, queryset=Images.objects.none())
        if postForm.is_valid() and formset.is_valid():
            post_form = postForm.save(commit=False)
            post_form.author = self.request.user
            post_form.save()
            for form in formset.cleaned_data:
                if form:
                    images = form['images']
                    photo = Images(post=post_form, images=images)
                    photo.save()
            return HttpResponseRedirect('/')
        return render(request, self.template_name, {'postForm': postForm, 'formset': formset})


class PostUpdateView(SuccessMessageMixin, UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/update.html'
    form_class = PostForm
    success_message = 'Bài viết đã được cập nhật!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(SuccessMessageMixin, UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_message = 'Xóa bài viết thành công!'
    success_url = '/'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        return context

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def PostLikeView(request, pk):
    if request.method == 'POST':
        user = request.user
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        _liked = user in post.liked.all()
        if _liked :
            post.liked.remove(user)
        else:
            post.liked.add(user)
    return redirect('post-detail', pk=post.id)


def about(request):
    countries = Country.objects.all()
    context = {
        'countries': countries
    }
    return render(request, 'blog/about.html', {'title': 'About', 'countries':countries})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>Blog About</h1>
{% endblock  %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/css/mdb.min.css" rel="stylesheet">
  {% if title %}
  <title>Blog Travel - {{ title }}</title>
  {% else %}
  <title>Blog Travel</title>
  {% endif %}
  <link rel="stylesheet" href="{% static 'blog/main.css' %}">
</head>

<body>
  {% include 'blog/navbar.html' %}
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'blog/images/pic1.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>IGO</h5>
          <p>Khám phá du lịch khắp việt nam cùng chúng tôi.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'blog/images/pic2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Đi khắp vùng miền trên cả nước</h5>
          <p>Nơi chia sẽ những địa điểm hay ho, thú vị ở Việt Nam.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'blog/images/pic3.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Hãy đến IGO</h5>
          <p>Tự tay viết lên những bài viết chia sẽ kinh nghiệm du lịch hữu ích cho mọi người.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}
    <br>
  </div>
  <!-- Footer -->
  <footer class="page-footer font-small unique-color-dark">
    <div class="container">
      <!-- Grid row-->
      <div class="row py-2 d-flex align-items-center"></div>
      <!-- Footer Links -->
      <div class="container text-center text-md-left mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase font-weight-bold">Thông tin</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p><a href="{% url 'blog-about' %}">Thông tin website</a></p>
          </div>
          <!-- Grid column -->
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold">Điều khoản</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <a href="#!">Điều khoản sử dụng</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase font-weight-bold">Liên hệ</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <i class="fas fa-home mr-3"></i>...</p>
            <p>
              <i class="fas fa-envelope mr-3"></i> admin@example.com</p>
            <p>
              <i class="fas fa-phone mr-3"></i>...</p>
            <p>
              <i class="fas fa-print mr-3"></i>...</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/"> IGO.com version-beta</a>
      </div>
      <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <!-- Optional JavaScript -->
  <!-- JQuery -->
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v7.0"
    nonce="9rkS8diz"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
  </script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/js/mdb.min.js">
  </script>
</body>

</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base1.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <!--First slide-->
        <div class="carousel-item active">
            <img class="d-block w-100" src="{{ object.image.url }}" alt="First slide">
        </div>
        <!--/Third slide-->
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->
<div class="media-body">
    <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{object.place}} {{ object.date_posted|date:"H:i d F, Y" }}</small>
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    <p class="article-content">{{ object.content|linebreaks }}</p>
    {% if object.author == user %}
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}" style="float: right;">Xóa</a>
    <a class="btn btn-info btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}" style="float: right;">Cập Nhật</a>
    {% endif %}
</div>
<br>
<br>
<div class="main-comment-section">
    <small class="text-muted">{{ post.liked.all.count }} lượt thích</small>
</div>
<form action="{% url 'like-post' post.pk %}" method='POST' style="float: right;">
    {% csrf_token %}
    {% if user.is_authenticated %}
    {% if user not in post.liked.all %}
    <button class="btn-primary" type="submit" name="post_id" value="{{ post.id }}"><i class="far fa-thumbs-up"
            aria-hidden="true"></i>Thích</button>
    {% else %}
    <button class="btn-primary" type="submit" name="post_id" value="{{ post.id }}"><i class="far fa-thumbs-up"
            aria-hidden="true"></i>Bỏ
        Thích</button>
    {% endif %}
    <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button" data-size="large"><a
            target="_blank"
            href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
            class="fb-xfbml-parse-ignore">Chia sẻ</a></div>
    {% endif %}

</form>
<div class="container">
    <div class="row gallery">
        <div id="mdb-lightbox-ui"></div>
        {% for p in post.images_set.all %}
        <figure class="col-md-4">
            <a href="{{ p.images.url }}" data-size="800x800">
                <img alt="picture" src="{{ p.images.url }}" class="img-fluid">
            </a>
        </figure>
        {% endfor %}
    </div>
</div>
<br>
<br>
<hr>
{% if user.is_authenticated %}
<form method='POST'>
    {% csrf_token %}
    <div class="card my-4">
        <h5 class="card-header">Bình luận bài viết</h5>
        <div class="card-body">
            {{ form|crispy }}
            <input type="submit" value="Gửi" class="btn btn-primary btn-sm">
        </div>
    </div>
</form>

<div class="container">
    <div class="be-comment-block">
        <h1 class="comments-title">Bình luận ({{ comments.count }})</h1>
        {% for comment in comments %}
        <div class="be-comment">
            <div class="be-img-comment">
                <a href="{% url 'user-posts' user.username %}">
                    <img src="{{ object.author.profile.image.url }}" alt="" class="be-ava-comment">
                </a>
            </div>
            <div class="be-comment-content">
                <span class="be-comment-name">
                    <a href="{% url 'user-posts' comment.user.username %}">{{ comment.user.get_full_name }}</a>
                </span>
                <span class="be-comment-time">
                    <i class="fa fa-clock-o"></i>
                    {{ comment.timestamp|date:"H:i d/m/Y" }}
                </span>
                <p class="be-comment-text">
                    {{comment.content}}
                </p>
                <p>{{ comment.likes.count }}</p>
                <footer class="footer-comment"><a class="comment-reply-btn" href="#">Reply</a></footer>
                <div class="comment-reply" style="display:none;">
                    {% for reply in comment.replies.all %}
                    <div class="be-comment">
                        <div class="be-img-comment">
                            <a href="{% url 'user-posts' user.username %}">
                                <img src="{{ object.author.profile.image.url }}" alt="" class="be-ava-comment">
                            </a>
                        </div>
                        <div class="be-comment-content">
                            <span class="be-comment-name">
                                <a href="{% url 'user-posts' reply.user.username %}">{{ reply.user.get_full_name }}</a>
                            </span>
                            <span class="be-comment-time">
                                <i class="fa fa-clock-o"></i>
                                {{ reply.timestamp|date:"H:i d/m/Y" }}
                            </span>
                            <p class="be-comment-text">
                                {{reply.content}}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                    <form action="." method="post">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <!-- Hidden input for parent comment.id -->
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <input class="btn btn-primary btn-sm" type="submit" value="Reply">
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<a href="{% url 'login' %}">Đăng nhập để bình luận bài viết</a>
<div class="container">
    <div class="be-comment-block">
        <h1 class="comments-title">Bình luận ({{ comments.count }})</h1>
        {% for comment in comments %}
        <div class="be-comment">
            <div class="be-img-comment">
                <a href="{% url 'user-posts' post.author.username %}">
                    <img src="{{ object.author.profile.image.url }}" alt="" class="be-ava-comment">
                </a>
            </div>
            <div class="be-comment-content">

                <span class="be-comment-name">
                    <a href="{% url 'user-posts' comment.user.username %}">{{ comment.user.get_full_name }}</a>
                </span>
                <span class="be-comment-time">
                    <i class="fa fa-clock-o"></i>
                    {{ comment.timestamp|date:"H:i d/m/Y" }}
                </span>
                <p class="be-comment-text">
                    {{comment.content}}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
<br>
<h3>Các bài viết liên quan:</h3>
<br>
<!-- Card deck -->
<div class="row row-cols-1 row-cols-md-3">
    {% for post in post_list %}
    {% if forloop.counter0|divisibleby:1 %}
    <!-- Card -->
    <div class="col mb-4">
        <div class="card">
            <!--Card image-->
            <div class="view overlay">
                <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
                <a href="{% url 'post-detail' post.id %}">
                    <div class="mask rgba-white-slight"></div>
                </a>
            </div>
            <!--Card content-->
            <div class="card-body">
                <!--Title-->
                <h4 class="card-title">{{ post.title }}</h4>
                <!--Text-->
                <p class="card-text">{{ post.content|safe|truncatewords:"20" }}</p>
                <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
                <a href="{% url 'post-detail' post.id %}" class="white-text d-flex justify-content-end">
                    <h5>Xem thêm <i class="fas fa-angle-double-right"></i></h5>
                </a>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock  %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<h3>Tạo bài viết</h3>
<div class="content-section">
    <form id="post_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ postForm|crispy }}
        {{ formset.management_form }}
        {{ formset|crispy }}
        <br>
        <button type="submit" class="btn btn-success">Đăng bài</button>
    </form>
</div>
{% endblock  %}